export default {
    rules: {
        'vue/no-unused-components': [
            'error',
            {
                ignoreWhenBindingPresent: true,
            },
        ],
        'vue/html-quotes': ['error', 'double', { 'avoidEscape': false }],
        'vue/no-v-text-v-html-on-component': 'off',
        'vue/component-name-in-template-casing': ['error', 'PascalCase'],
        'vue/no-mutating-props': 'error',
        'vue/no-v-html': 'error',
        'vue/require-default-prop': 'error',
        'vue/require-prop-types': 'error',
        'vue/valid-v-slot': 'error',
        'vue/no-unused-vars': 'error',
        'vue/multi-word-component-names': 'error',
        'vue/no-reserved-component-names': 'error',
        'vue/attributes-order': ['error', {
            order: [
                'DEFINITION',
                'LIST_RENDERING',
                'CONDITIONALS',
                'RENDER_MODIFIERS',
                'GLOBAL',
                'UNIQUE',
                'TWO_WAY_BINDING',
                'OTHER_DIRECTIVES',
                'OTHER_ATTR',
                'EVENTS',
                'CONTENT'
            ]
        }],
        'vue/order-in-components': ['error', {
            order: [
                'el',
                'name',
                'key',
                'parent',
                'functional',
                ['delimiters', 'comments'],
                ['components', 'directives', 'filters'],
                'extends',
                'mixins',
                ['provide', 'inject'],
                'ROUTER_GUARDS',
                'layout',
                'middleware',
                'validate',
                'scrollToTop',
                'transition',
                'loading',
                'inheritAttrs',
                'model',
                ['props', 'propsData'],
                'emits',
                'setup',
                'asyncData',
                'data',
                'fetch',
                'head',
                'computed',
                'watch',
                'watchQuery',
                'LIFECYCLE_HOOKS',
                'methods',
                ['template', 'render'],
                'renderError'
            ]
        }],
        'vue/this-in-template': 'error',
        'vue/no-duplicate-attr-inheritance': 'error',
        'vue/no-duplicate-attributes': 'error',
        'vue/no-irregular-whitespace': 'error',
        'vue/no-reserved-keys': 'error',
        'vue/no-shared-component-data': 'error',
        'vue/no-template-key': 'error',
        'vue/no-textarea-mustache': 'error',
        'vue/no-use-v-if-with-v-for': 'error',
        'vue/require-component-is': 'error',
        'vue/require-render-return': 'error',
        'vue/require-v-for-key': 'error',
        'vue/require-valid-default-prop': 'error',
        'vue/return-in-computed-property': 'error',
        'vue/use-v-on-exact': 'error',
        'vue/v-bind-style': ['error', 'shorthand'],
        'vue/v-on-style': ['error', 'shorthand'],
        'vue/v-slot-style': ['error', 'shorthand'],
    }
}